# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170930_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(default='', max_length=25)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Positions')),
            ],
        ),
    ]
