# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskills',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.Positions'),
        ),
    ]
