# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171002_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
    ]
