# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170930_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
